/* auto-generated by NAPI-RS */
/* eslint-disable */
export interface MemoryCandidate {
  record: MemoryRecord
  confidence: number
  score: ScoreBreakdown
}

export declare const enum MemoryLayer {
  Working = 0,
  Episodic = 1,
  Semantic = 2,
  Procedural = 3
}

export interface MemoryRecord {
  id: string
  layer: MemoryLayer
  content: string
  timestampMs: number
  metadata?: Record<string, string>
}

export declare function retrieve(query: string, candidates: Array<MemoryRecord>, opts: RetrieveOptions): Array<MemoryCandidate>

export interface RetrieveOptions {
  topK: number
  minScore: number
}

export interface ScoreBreakdown {
  similarity: number
  recency: number
  layerWeight: number
}
