/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare class JsMemoryEngine {
  constructor()
  retrieve(input: JsRetrieveInput): Array<JsRetrievedMemory>
  explain(input: JsRetrieveInput): JsRetrievalExplanation
}

export interface JsBaseMemory {
  id: string
  kind: MemoryLayer
  content: string
  createdAt: number
  lastAccessedAt: number
  importance: number
  metadata?: Record<string, string>
}

export interface JsCandidateMemory {
  base: JsBaseMemory
  semantic?: JsSemanticPayload
  episodic?: JsEpisodicPayload
  working?: JsWorkingPayload
  procedural?: JsProceduralPayload
}

export interface JsEpisodicPayload {
  eventTime: number
  durationMs?: number
}

export interface JsProceduralPayload {
  triggers: Array<string>
  config?: string
  version?: string
}

export interface JsRetrievalExplanation {
  considered: number
  returned: number
  memories: Array<JsRetrievedMemory>
}

export interface JsRetrievedMemory {
  id: string
  kind: MemoryLayer
  score: number
  reasons: Array<JsScoreReason>
}

export interface JsRetrieveInput {
  queryEmbedding?: Array<number>
  candidates: Array<JsCandidateMemory>
  limit: number
  now: number
}

export interface JsScoreReason {
  kind: JsScoreReasonKind
  score?: number
  trigger?: string
}

export declare const enum JsScoreReasonKind {
  Semantic = 0,
  Recency = 1,
  Working = 2,
  Procedural = 3,
  Importance = 4
}

export interface JsSemanticPayload {
  embedding: Array<number>
}

export interface JsWorkingPayload {
  expiresAt?: number
  size?: number
}

export declare const enum MemoryLayer {
  Semantic = 0,
  Episodic = 1,
  Working = 2,
  Procedural = 3
}
