/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare class JsMemoryEngine {
  constructor();
  retrieve(input: JsRetrieveInput): Array<JsRetrievedMemory>;
  explain(input: JsRetrieveInput): JsRetrievalExplanation;
}

export interface JsBaseMemory {
  id: string;
  kind: MemoryKind;
  content: string;
  createdAt: number;
  lastAccessedAt: number;
  importance: number;
  metadata?: Record<string, string>;
}

export interface JsCandidateMemory {
  base: JsBaseMemory;
  semantic?: JsSemanticPayload;
  episodic?: JsEpisodicPayload;
  working?: JsWorkingPayload;
  procedural?: JsProceduralPayload;
}

export interface JsEpisodicPayload {
  eventTime: number;
  durationMs?: number;
}

export interface JsProceduralPayload {
  triggers: Array<string>;
  config?: string;
  version?: string;
}

export interface JsRetrievalExplanation {
  considered: number;
  returned: number;
  memories: Array<JsRetrievedMemory>;
}

export interface JsRetrievedMemory {
  id: string;
  kind: MemoryKind;
  score: number;
  reasons: Array<JsScoreReason>;
}

export interface JsRetrieveInput {
  queryEmbedding?: Array<number>;
  candidates: Array<JsCandidateMemory>;
  limit: number;
  now: number;
}

export interface JsScoreReason {
  kind: ScoreReasonKind;
  score?: number;
  trigger?: string;
}

export interface JsSemanticPayload {
  embedding: Array<number>;
}

export interface JsWorkingPayload {
  expiresAt?: number;
  size?: number;
}

export enum MemoryKind {
  Semantic = "Semantic",
  Episodic = "Episodic",
  Working = "Working",
  Procedural = "Procedural",
}

export enum ScoreReasonKind {
  Semantic = "Semantic",
  Recency = "Recency",
  Working = "Working",
  Procedural = "Procedural",
  Importance = "Importance",
}
